---
abstract: 'yet another github client command'
author:
  - 'Tokuhiro Matsuno <tokuhirom @ GMAIL COM>'
build_requires:
  Test::More: 0.98
  Test::Requires: 0
configure_requires:
  Module::Build::Tiny: 0
dynamic_config: 0
generated_by: 'Minilla/v0.0.49, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ph
provides:
  App::ph:
    file: lib/App/ph.pm
    version: 0.06
requires:
  IPC::System::Simple: 0
  Pithub: 0
  Sys::Hostname: 0
  Term::ANSIColor: 0
  Term::ReadKey: 0
  autodie: 0
  parent: 0
resources:
  bugtracker: https://github.com/tokuhirom/ph/issues
  homepage: https://github.com/tokuhirom/ph
  repository: git://github.com/tokuhirom/ph.git
version: 0.06
