---
abstract: 'yet another github client command'
author:
  - 'Tokuhiro Matsuno <tokuhirom @ GMAIL COM>'
build_requires:
  Test::More: 0.98
  Test::Requires: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
  Module::Build::Tiny: 0
dynamic_config: 0
generated_by: 'Minilla/v0.0.49, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ph
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
provides:
  App::ph:
    file: lib/App/ph.pm
    version: 0.07
requires:
  IPC::System::Simple: 0
  Pithub: 0
  Sys::Hostname: 0
  Term::ANSIColor: 0
  Term::ReadKey: 0
  autodie: 0
  parent: 0
  perl: 5.008008
resources:
  bugtracker: https://github.com/tokuhirom/ph/issues
  homepage: https://github.com/tokuhirom/ph
  repository: git://github.com/tokuhirom/ph.git
version: 0.07
x_contributors:
  - 'mattn <mattn.jp@gmail.com>'
  - 'Jesse Luehrs <doy@tozt.net>'
  - 'Chris Weyl <cweyl@alumni.drew.edu>'
  - 'tokuhirom <tokuhirom@gmail.com>'
