---
abstract: 'yet another github client command'
author:
  - 'Tokuhiro Matsuno <tokuhirom @ GMAIL COM>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.11.0, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ph
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  App::ph:
    file: lib/App/ph.pm
    version: 0.09
requires:
  Encode: 0
  Encode::Locale: 0
  Getopt::Long: 0
  HTTP::Request: 0
  IPC::System::Simple: 0
  JSON: 0
  LWP::UserAgent: 0
  Pithub: 0
  Pod::Usage: 0
  Sys::Hostname: 0
  Term::ANSIColor: 0
  Term::ReadKey: 0
  autodie: 0
  parent: 0
  perl: 5.010000
resources:
  bugtracker: https://github.com/tokuhirom/ph/issues
  homepage: https://github.com/tokuhirom/ph
  repository: git://github.com/tokuhirom/ph.git
version: 0.09
x_contributors:
  - 'mattn <mattn.jp@gmail.com>'
  - 'Jesse Luehrs <doy@tozt.net>'
  - 'Chris Weyl <cweyl@alumni.drew.edu>'
  - 'Syohei YOSHIDA <syohex@gmail.com>'
  - 'Neil Bowers <neil@bowers.com>'
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
